name: lof
channels:
  - https://repo.anaconda.com/pkgs/free
  - defaults
dependencies:
  - blas=1.0
  - future=0.18.2
  - jpeg=9b
  - lame=3.100
  - libpng=1.6.35
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pickleshare=0.7.5
  - pip=20.0.2
  - pygments=2.5.2
  - python=3.8.1
  - python-dateutil=2.8.1
  - wheel=0.34.2
  - pip:
    - celluloid==0.2.0
    - matplotlib==3.1.3
    - scipy==1.4.1