name: lof
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - certifi=2020.6.20
  - future=0.18.2
  - lame=3.100
  - nettle=3.4.1
  - openssl=1.1.1g
  - x264=1!152.20180806
  - _libgcc_mutex=0.1
  - astroid=2.4.2
  - backcall=0.1.0
  - blas=1.0
  - cffi=1.11.5
  - decorator=4.4.1
  - freetype=2.9.1
  - intel-openmp=2019.1
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.16.0
  - jpeg=9b
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.35
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - mccabe=0.6.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - parso=0.6.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=20.0.2
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pylint=2.5.3
  - python=3.8.1
  - python-dateutil=2.8.1
  - pyzmq=18.1.1
  - readline=7.0
  - scipy=1.1.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toml=0.10.1
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - celluloid==0.2.0
    - matplotlib==3.1.3